stages:
  - test
  - build
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  VERCEL_ORG_ID: "ton_org_id"
  VERCEL_PROJECT_ID: "ton_project_id"

cache:
  paths:
    - .cache/pip

test:
  stage: test
  image: python:3.12
  script:
    - pip install -r requirements.txt
    - pytest -v

docker-build:
  stage: build
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker build -t bank-account:latest .
  only:
    - merge_requests
    - main

deploy-vercel:
  stage: deploy
  image: node:20
  script:
    - npm install -g vercel
    - cd bank-account-ui
    - vercel pull --yes --environment=production --token $VERCEL_TOKEN
    - vercel build --prod --token $VERCEL_TOKEN
    - vercel deploy --prebuilt --prod --token $VERCEL_TOKEN
  only:
    - main
